version: '3.5'

services:

  pulsar:
    container_name: pulsar
    image: 'apachepulsar/pulsar:2.5.0'
    ports:
      - '8080:8080'
      - '6650:6650'
    expose:
      - 8080
      - 6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: |
      /bin/bash -c "bin/apply-config-from-env.py conf/standalone.conf && bin/pulsar standalone"

  pulsar-express:
    container_name: pulsar-express
    image: bbonnin/pulsar-express:0.5.1
    depends_on:
      - pulsar
    ports:
      - '3000:3000'
    environment:
      SERVICE_URL: 'http://pulsar:8080'

networks:
  default:
    name: pulsar-network
    driver: bridge
